// Include the burn model generated by build.rs from our ONNX file.
// OUT_DIR is set by Cargo and points to the build output directory.
// The generated file defines `Model<B>` with pretrained weights loaded
// via `Model::from_file(path, device)`.
include!(concat!(env!("OUT_DIR"), "/model/resnet18_encoder.rs"));

use burn::prelude::*;

/// Wrapper that locates the weight file and returns a ready-to-use encoder.
///
/// The `.bpk` file is generated alongside the binary in Cargo's output dir.
/// During development `cargo run` handles this automatically.
pub fn load_encoder<B: Backend>(device: &B::Device) -> Model<B> {
    let weights = concat!(env!("OUT_DIR"), "/model/resnet18_encoder.bpk");
    Model::from_file(weights, device)
}
